### ISSUE TITLE
No Method Error backend= & queue=

### ISSUE THREAD

**Issue by grzegorz-jakubiak** [mhfs/devise-async#105]
Hi, I use Rails 5.1.4 and Sidekiq and I want to configure devise-async to send my devise mails but unfortunately when I run my environment via foreman Procfile I get these no methods errors. I don't get it because docs specifically say if I want to use sidekiq I have to configure devise-async like this:

```
Devise::Async.setup do |config|
  config.enabled = true
  config.backend = :sidekiq
  config.queue = :mailers
end
```

**Comment by baschtl** [comment]
Hi @greggzst,

~~it is quite hard to help you when you do not specify the errors you get.~~~

I saw the issue title now.

Still, please use ActiveJob and the newest 1.0.0 release of devise-async with Rails 5. The options you try to set are not available anymore. The readme reflects that now.

**Comment by grzegorz-jakubiak** [comment]
Hi @baschtl,

Sorry bout that. Here is the message I get every time I start my app with foreman:

```
/Users/grzegorz/Documents/own/hms/config/initializers/devise_async.rb:3:in `block in <top (required)>': undefined method `backend=' for Devise::Async:Module (NoMethodError)
18:52:07 web.1    | 	from /Users/grzegorz/.rvm/gems/ruby-2.4.1@hms/gems/devise-async-1.0.0/lib/devise/async.rb:19:in `setup'
18:52:07 web.1    | 	from /Users/grzegorz/Documents/own/hms/config/initializers/devise_async.rb:1:in `<top (required)>'
18:52:07 web.1    | 	from /Users/grzegorz/.rvm/gems/ruby-2.4.1@hms/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:286:in `load'
18:52:07 web.1    | 	from /Users/grzegorz/.rvm/gems/ruby-2.4.1@hms/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:286:in `block in load'
18:52:07 web.1    | 	from /Users/grzegorz/.rvm/gems/ruby-2.4.1@hms/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:258:in `load_dependency'
18:52:07 web.1    | 	from /Users/grzegorz/.rvm/gems/ruby-2.4.1@hms/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:286:in `load'
18:52:07 web.1    | 	from /Users/grzegorz/.rvm/gems/ruby-2.4.1@hms/gems/railties-5.1.4/lib/rails/engine.rb:655:in `block in load_config_initializer'
18:52:07 web.1    | 	from /Users/grzegorz/.rvm/gems/ruby-2.4.1@hms/gems/activesupport-5.1.4/lib/active_support/notifications.rb:168:in `instrument'
18:52:07 web.1    | 	from /Users/grzegorz/.rvm/gems/ruby-2.4.1@hms/gems/railties-5.1.4/lib/rails/engine.rb:654:in `load_config_initializer'
18:52:07 worker.1 | undefined method `backend=' for Devise::Async:Module
18:52:07 web.1    | 	from /Users/grzegorz/.rvm/gems/ruby-2.4.1@hms/gems/railties-5.1.4/lib/rails/engine.rb:612:in `block (2 levels) in <class:Engine>'
18:52:07 worker.1 | /Users/grzegorz/Documents/own/hms/config/initializers/devise_async.rb:3:in `block in <top (required)>'
18:52:07 web.1    | 	from /Users/grzegorz/.rvm/gems/ruby-2.4.1@hms/gems/railties-5.1.4/lib/rails/engine.rb:611:in `each'
18:52:07 worker.1 | /Users/grzegorz/.rvm/gems/ruby-2.4.1@hms/gems/devise-async-1.0.0/lib/devise/async.rb:19:in `setup'
18:52:07 web.1    | 	from /Users/grzegorz/.rvm/gems/ruby-2.4.1@hms/gems/railties-5.1.4/lib/rails/engine.rb:611:in `block in <class:Engine>'
18:52:07 worker.1 | /Users/grzegorz/Documents/own/hms/config/initializers/devise_async.rb:1:in `<top (required)>'
18:52:07 web.1    | 	from /Users/grzegorz/.rvm/gems/ruby-2.4.1@hms/gems/railties-5.1.4/lib/rails/initializable.rb:30:in `instance_exec'
18:52:07 worker.1 | /Users/grzegorz/.rvm/gems/ruby-2.4.1@hms/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:286:in `load'
18:52:07 web.1    | 	from /Users/grzegorz/.rvm/gems/ruby-2.4.1@hms/gems/railties-5.1.4/lib/rails/initializable.rb:30:in `run'
18:52:07 worker.1 | /Users/grzegorz/.rvm/gems/ruby-2.4.1@hms/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:286:in `block in load'
18:52:07 web.1    | 	from /Users/grzegorz/.rvm/gems/ruby-2.4.1@hms/gems/railties-5.1.4/lib/rails/initializable.rb:59:in `block in run_initializers'
18:52:07 worker.1 | /Users/grzegorz/.rvm/gems/ruby-2.4.1@hms/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:258:in `load_dependency'
18:52:07 web.1    | 	from /Users/grzegorz/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/tsort.rb:228:in `block in tsort_each'
18:52:07 worker.1 | /Users/grzegorz/.rvm/gems/ruby-2.4.1@hms/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:286:in `load'
18:52:07 web.1    | 	from /Users/grzegorz/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
18:52:07 worker.1 | /Users/grzegorz/.rvm/gems/ruby-2.4.1@hms/gems/railties-5.1.4/lib/rails/engine.rb:655:in `block in load_config_initializer'
18:52:07 web.1    | 	from /Users/grzegorz/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/tsort.rb:422:in `block (2 levels) in each_strongly_connected_component_from'
18:52:07 worker.1 | /Users/grzegorz/.rvm/gems/ruby-2.4.1@hms/gems/activesupport-5.1.4/lib/active_support/notifications.rb:168:in `instrument'
18:52:07 web.1    | 	from /Users/grzegorz/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/tsort.rb:431:in `each_strongly_connected_component_from'
18:52:07 worker.1 | /Users/grzegorz/.rvm/gems/ruby-2.4.1@hms/gems/railties-5.1.4/lib/rails/engine.rb:654:in `load_config_initializer'
18:52:07 web.1    | 	from /Users/grzegorz/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/tsort.rb:421:in `block in each_strongly_connected_component_from'
18:52:07 worker.1 | /Users/grzegorz/.rvm/gems/ruby-2.4.1@hms/gems/railties-5.1.4/lib/rails/engine.rb:612:in `block (2 levels) in <class:Engine>'
18:52:07 web.1    | 	from /Users/grzegorz/.rvm/gems/ruby-2.4.1@hms/gems/railties-5.1.4/lib/rails/initializable.rb:48:in `each'
18:52:07 worker.1 | /Users/grzegorz/.rvm/gems/ruby-2.4.1@hms/gems/railties-5.1.4/lib/rails/engine.rb:611:in `each'
18:52:07 web.1    | 	from /Users/grzegorz/.rvm/gems/ruby-2.4.1@hms/gems/railties-5.1.4/lib/rails/initializable.rb:48:in `tsort_each_child'
18:52:07 worker.1 | /Users/grzegorz/.rvm/gems/ruby-2.4.1@hms/gems/railties-5.1.4/lib/rails/engine.rb:611:in `block in <class:Engine>'
18:52:07 web.1    | 	from /Users/grzegorz/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/tsort.rb:415:in `call'
18:52:07 worker.1 | /Users/grzegorz/.rvm/gems/ruby-2.4.1@hms/gems/railties-5.1.4/lib/rails/initializable.rb:30:in `instance_exec'
18:52:07 web.1    | 	from /Users/grzegorz/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/tsort.rb:415:in `each_strongly_connected_component_from'
18:52:07 worker.1 | /Users/grzegorz/.rvm/gems/ruby-2.4.1@hms/gems/railties-5.1.4/lib/rails/initializable.rb:30:in `run'
18:52:07 web.1    | 	from /Users/grzegorz/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/tsort.rb:349:in `block in each_strongly_connected_component'
18:52:07 worker.1 | /Users/grzegorz/.rvm/gems/ruby-2.4.1@hms/gems/railties-5.1.4/lib/rails/initializable.rb:59:in `block in run_initializers'
18:52:07 web.1    | 	from /Users/grzegorz/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/tsort.rb:347:in `each'
18:52:07 worker.1 | /Users/grzegorz/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/tsort.rb:228:in `block in tsort_each'
18:52:07 web.1    | 	from /Users/grzegorz/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/tsort.rb:347:in `call'
18:52:07 worker.1 | /Users/grzegorz/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
18:52:07 web.1    | 	from /Users/grzegorz/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/tsort.rb:347:in `each_strongly_connected_component'
18:52:07 worker.1 | /Users/grzegorz/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/tsort.rb:422:in `block (2 levels) in each_strongly_connected_component_from'
18:52:07 web.1    | 	from /Users/grzegorz/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/tsort.rb:226:in `tsort_each'
18:52:07 worker.1 | /Users/grzegorz/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/tsort.rb:431:in `each_strongly_connected_component_from'
18:52:07 web.1    | 	from /Users/grzegorz/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/tsort.rb:205:in `tsort_each'
18:52:07 worker.1 | /Users/grzegorz/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/tsort.rb:421:in `block in each_strongly_connected_component_from'
18:52:07 web.1    | 	from /Users/grzegorz/.rvm/gems/ruby-2.4.1@hms/gems/railties-5.1.4/lib/rails/initializable.rb:58:in `run_initializers'
18:52:07 worker.1 | /Users/grzegorz/.rvm/gems/ruby-2.4.1@hms/gems/railties-5.1.4/lib/rails/initializable.rb:48:in `each'
18:52:07 web.1    | 	from /Users/grzegorz/.rvm/gems/ruby-2.4.1@hms/gems/railties-5.1.4/lib/rails/application.rb:353:in `initialize!'
18:52:07 worker.1 | /Users/grzegorz/.rvm/gems/ruby-2.4.1@hms/gems/railties-5.1.4/lib/rails/initializable.rb:48:in `tsort_each_child'
18:52:07 web.1    | 	from /Users/grzegorz/Documents/own/hms/config/environment.rb:5:in `<top (required)>'
18:52:07 worker.1 | /Users/grzegorz/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/tsort.rb:415:in `call'
18:52:07 web.1    | 	from config.ru:3:in `require_relative'
18:52:07 worker.1 | /Users/grzegorz/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/tsort.rb:415:in `each_strongly_connected_component_from'
18:52:07 web.1    | 	from config.ru:3:in `block in <main>'
18:52:07 worker.1 | /Users/grzegorz/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/tsort.rb:349:in `block in each_strongly_connected_component'
18:52:07 web.1    | 	from /Users/grzegorz/.rvm/gems/ruby-2.4.1@hms/gems/rack-2.0.3/lib/rack/builder.rb:55:in `instance_eval'
18:52:07 worker.1 | /Users/grzegorz/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/tsort.rb:347:in `each'
18:52:07 web.1    | 	from /Users/grzegorz/.rvm/gems/ruby-2.4.1@hms/gems/rack-2.0.3/lib/rack/builder.rb:55:in `initialize'
18:52:07 worker.1 | /Users/grzegorz/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/tsort.rb:347:in `call'
18:52:07 web.1    | 	from config.ru:in `new'
18:52:07 worker.1 | /Users/grzegorz/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/tsort.rb:347:in `each_strongly_connected_component'
18:52:07 web.1    | 	from config.ru:in `<main>'
18:52:07 worker.1 | /Users/grzegorz/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/tsort.rb:226:in `tsort_each'
18:52:07 web.1    | 	from /Users/grzegorz/.rvm/gems/ruby-2.4.1@hms/gems/rack-2.0.3/lib/rack/builder.rb:49:in `eval'
18:52:07 worker.1 | /Users/grzegorz/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/tsort.rb:205:in `tsort_each'
18:52:07 web.1    | 	from /Users/grzegorz/.rvm/gems/ruby-2.4.1@hms/gems/rack-2.0.3/lib/rack/builder.rb:49:in `new_from_string'
18:52:07 worker.1 | /Users/grzegorz/.rvm/gems/ruby-2.4.1@hms/gems/railties-5.1.4/lib/rails/initializable.rb:58:in `run_initializers'
18:52:07 web.1    | 	from /Users/grzegorz/.rvm/gems/ruby-2.4.1@hms/gems/rack-2.0.3/lib/rack/builder.rb:40:in `parse_file'
18:52:07 worker.1 | /Users/grzegorz/.rvm/gems/ruby-2.4.1@hms/gems/railties-5.1.4/lib/rails/application.rb:353:in `initialize!'
18:52:07 web.1    | 	from /Users/grzegorz/.rvm/gems/ruby-2.4.1@hms/gems/rack-2.0.3/lib/rack/server.rb:319:in `build_app_and_options_from_config'
18:52:07 worker.1 | /Users/grzegorz/Documents/own/hms/config/environment.rb:5:in `<top (required)>'
18:52:07 web.1    | 	from /Users/grzegorz/.rvm/gems/ruby-2.4.1@hms/gems/rack-2.0.3/lib/rack/server.rb:219:in `app'
18:52:07 worker.1 | /Users/grzegorz/.rvm/gems/ruby-2.4.1@hms/gems/sidekiq-5.0.4/lib/sidekiq/cli.rb:257:in `require'
18:52:07 web.1    | 	from /Users/grzegorz/.rvm/gems/ruby-2.4.1@hms/gems/railties-5.1.4/lib/rails/commands/server/server_command.rb:24:in `app'
18:52:07 worker.1 | /Users/grzegorz/.rvm/gems/ruby-2.4.1@hms/gems/sidekiq-5.0.4/lib/sidekiq/cli.rb:257:in `boot_system'
18:52:07 web.1    | 	from /Users/grzegorz/.rvm/gems/ruby-2.4.1@hms/gems/rack-2.0.3/lib/rack/server.rb:354:in `wrapped_app'
18:52:07 worker.1 | /Users/grzegorz/.rvm/gems/ruby-2.4.1@hms/gems/sidekiq-5.0.4/lib/sidekiq/cli.rb:54:in `run'
18:52:07 web.1    | 	from /Users/grzegorz/.rvm/gems/ruby-2.4.1@hms/gems/railties-5.1.4/lib/rails/commands/server/server_command.rb:80:in `log_to_stdout'
18:52:07 worker.1 | /Users/grzegorz/.rvm/gems/ruby-2.4.1@hms/gems/sidekiq-5.0.4/bin/sidekiq:12:in `<top (required)>'
18:52:07 web.1    | 	from /Users/grzegorz/.rvm/gems/ruby-2.4.1@hms/gems/railties-5.1.4/lib/rails/commands/server/server_command.rb:42:in `start'
18:52:07 worker.1 | /Users/grzegorz/.rvm/gems/ruby-2.4.1@hms/bin/sidekiq:23:in `load'
18:52:07 web.1    | 	from /Users/grzegorz/.rvm/gems/ruby-2.4.1@hms/gems/railties-5.1.4/lib/rails/commands/server/server_command.rb:135:in `block in perform'
18:52:07 worker.1 | /Users/grzegorz/.rvm/gems/ruby-2.4.1@hms/bin/sidekiq:23:in `<main>'
18:52:07 web.1    | 	from /Users/grzegorz/.rvm/gems/ruby-2.4.1@hms/gems/railties-5.1.4/lib/rails/commands/server/server_command.rb:130:in `tap'
18:52:07 worker.1 | /Users/grzegorz/.rvm/gems/ruby-2.4.1@hms/bin/ruby_executable_hooks:15:in `eval'
18:52:07 web.1    | 	from /Users/grzegorz/.rvm/gems/ruby-2.4.1@hms/gems/railties-5.1.4/lib/rails/commands/server/server_command.rb:130:in `perform'
18:52:07 worker.1 | /Users/grzegorz/.rvm/gems/ruby-2.4.1@hms/bin/ruby_executable_hooks:15:in `<main>'
18:52:07 web.1    | 	from /Users/grzegorz/.rvm/gems/ruby-2.4.1@hms/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
18:52:07 web.1    | 	from /Users/grzegorz/.rvm/gems/ruby-2.4.1@hms/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
18:52:07 web.1    | 	from /Users/grzegorz/.rvm/gems/ruby-2.4.1@hms/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
18:52:07 web.1    | 	from /Users/grzegorz/.rvm/gems/ruby-2.4.1@hms/gems/railties-5.1.4/lib/rails/command/base.rb:63:in `perform'
18:52:07 web.1    | 	from /Users/grzegorz/.rvm/gems/ruby-2.4.1@hms/gems/railties-5.1.4/lib/rails/command.rb:44:in `invoke'
18:52:07 web.1    | 	from /Users/grzegorz/.rvm/gems/ruby-2.4.1@hms/gems/railties-5.1.4/lib/rails/commands.rb:16:in `<top (required)>'
18:52:07 web.1    | 	from /Users/grzegorz/Documents/own/hms/bin/rails:9:in `require'
18:52:07 web.1    | 	from /Users/grzegorz/Documents/own/hms/bin/rails:9:in `<top (required)>'
18:52:07 web.1    | 	from /Users/grzegorz/.rvm/gems/ruby-2.4.1@hms/gems/spring-2.0.2/lib/spring/client/rails.rb:28:in `load'
18:52:07 web.1    | 	from /Users/grzegorz/.rvm/gems/ruby-2.4.1@hms/gems/spring-2.0.2/lib/spring/client/rails.rb:28:in `call'
18:52:07 web.1    | 	from /Users/grzegorz/.rvm/gems/ruby-2.4.1@hms/gems/spring-2.0.2/lib/spring/client/command.rb:7:in `call'
18:52:07 web.1    | 	from /Users/grzegorz/.rvm/gems/ruby-2.4.1@hms/gems/spring-2.0.2/lib/spring/client.rb:30:in `run'
18:52:07 web.1    | 	from /Users/grzegorz/.rvm/gems/ruby-2.4.1@hms/gems/spring-2.0.2/bin/spring:49:in `<top (required)>'
18:52:07 web.1    | 	from /Users/grzegorz/.rvm/gems/ruby-2.4.1@hms/gems/spring-2.0.2/lib/spring/binstub.rb:31:in `load'
18:52:07 web.1    | 	from /Users/grzegorz/.rvm/gems/ruby-2.4.1@hms/gems/spring-2.0.2/lib/spring/binstub.rb:31:in `<top (required)>'
18:52:07 web.1    | 	from /Users/grzegorz/Documents/own/hms/bin/spring:15:in `require'
18:52:07 web.1    | 	from /Users/grzegorz/Documents/own/hms/bin/spring:15:in `<top (required)>'
18:52:07 web.1    | 	from bin/rails:3:in `load'
18:52:07 web.1    | 	from bin/rails:3:in `<main>'

```
I use the newest release of devise-async but I don't really understand what you mean by using ActiveJob. I didn't see anything about ActiveJob in this [tutorial](https://github.com/plataformatec/devise/wiki/How-To:-Send-devise-emails-in-background-(Resque,-Sidekiq-and-Delayed::Job)) I mean anything that said I had to use it.

**Comment by baschtl** [comment]
This is old information. Please have a look at the readme of _this_ gem.

As I wrote before, the latest release of _this_ gem only works with ActiveJob. So, set up ActiveJob first and then you can use devise-async with devise to send your devise email delayed.

**Comment by zeitnot** [comment]
@baschtl I have the same problem. I have looked at readme but there is nothing to help me. What do you mean setting up ActiveJob?

**Comment by gaborszakacs** [comment]
@zeitnot 
1. Make sure you use Rails 4.2+, since Active Job was introduced in 4.2
2. Remove `config.backend` and `config.queue` from your devise-async configuration.
3. Add `config.active_job.queue_adapter = :sidekiq` to your `application.rb` [(more info)](http://guides.rubyonrails.org/active_job_basics.html#backends)
4. Email delivery jobs will be added to the `mailers` queue by default so [make sure](https://github.com/mperham/sidekiq/wiki/Active+Job#action-mailer) sidekiq starts processing that queue or if you are on Rails 5+, you can customize it by adding `config.action_mailer.deliver_later_queue_name = 'yourmailerqueue'` so you can use the same queue you used before with devise-async < 1.0

**Comment by zeitnot** [comment]
@gaborszakacs thanks. That fixes it.
