### ISSUE TITLE
failure in jruby

### ISSUE THREAD

**Issue by jjb** [mhfs/devise-async#44]
I'm using sidekiq, rails 4.

Everything works well under MRI 2.1. In JRuby 1.7.6, I get this:

```
NoMethodError: undefined method `devise_mailer' for #<User:0x1e077d66>
```

I'm exploring what the problem could be. The full stack trace is below.

```
2013-11-20T21:11:17Z 51784 TID-6gc ERROR: Sidekiq::Processor crashed!
NoMethodError: undefined method `devise_mailer' for #<User:0x1e077d66>

org/jruby/RubyBasicObject.java:1497:in `method_missing'
/Users/john/.rbenv/versions/jruby-1.7.6/lib/ruby/gems/shared/gems/activemodel-4.0.1/lib/active_model/attribute_methods.rb:436:in `method_missing'
/Users/john/.rbenv/versions/jruby-1.7.6/lib/ruby/gems/shared/gems/activerecord-4.0.1/lib/active_record/attribute_methods.rb:155:in `method_missing'
/Users/john/.rbenv/versions/jruby-1.7.6/lib/ruby/gems/shared/gems/rolify-3.2.0/lib/rolify/role.rb:73:in `method_missing'
org/jruby/RubyKernel.java:1958:in `public_send'
/Users/john/.rbenv/versions/jruby-1.7.6/lib/ruby/gems/shared/gems/activesupport-4.0.1/lib/active_support/core_ext/object/try.rb:45:in `try'
/Users/john/.rbenv/versions/jruby-1.7.6/lib/ruby/gems/shared/gems/devise-async-0.9.0/lib/devise/async/backend/base.rb:22:in `mailer_class'
/Users/john/.rbenv/versions/jruby-1.7.6/lib/ruby/gems/shared/gems/devise-async-0.9.0/lib/devise/async/backend/base.rb:16:in `perform'
/Users/john/.rbenv/versions/jruby-1.7.6/lib/ruby/gems/shared/gems/sidekiq-2.16.1/lib/sidekiq/processor.rb:48:in `process'
org/jruby/RubyProc.java:271:in `call'
/Users/john/.rbenv/versions/jruby-1.7.6/lib/ruby/gems/shared/gems/sidekiq-2.16.1/lib/sidekiq/middleware/chain.rb:119:in `invoke'
/Users/john/.rbenv/versions/jruby-1.7.6/lib/ruby/gems/shared/gems/rollbar-0.11.8/lib/rollbar/sidekiq.rb:7:in `call'
/Users/john/.rbenv/versions/jruby-1.7.6/lib/ruby/gems/shared/gems/sidekiq-2.16.1/lib/sidekiq/middleware/chain.rb:121:in `invoke'
/Users/john/.rbenv/versions/jruby-1.7.6/lib/ruby/gems/shared/gems/newrelic_rpm-3.6.9.171/lib/new_relic/agent/instrumentation/sidekiq.rb:30:in `call'
/Users/john/.rbenv/versions/jruby-1.7.6/lib/ruby/gems/shared/gems/newrelic_rpm-3.6.9.171/lib/new_relic/agent/instrumentation/controller_instrumentation.rb:339:in `perform_action_with_newrelic_trace'
/Users/john/.rbenv/versions/jruby-1.7.6/lib/ruby/gems/shared/gems/newrelic_rpm-3.6.9.171/lib/new_relic/agent/instrumentation/sidekiq.rb:21:in `call'
/Users/john/.rbenv/versions/jruby-1.7.6/lib/ruby/gems/shared/gems/sidekiq-2.16.1/lib/sidekiq/middleware/chain.rb:121:in `invoke'
/Users/john/.rbenv/versions/jruby-1.7.6/lib/ruby/gems/shared/gems/sidekiq-2.16.1/lib/sidekiq/middleware/server/active_record.rb:6:in `call'
/Users/john/.rbenv/versions/jruby-1.7.6/lib/ruby/gems/shared/gems/sidekiq-2.16.1/lib/sidekiq/middleware/chain.rb:121:in `invoke'
/Users/john/.rbenv/versions/jruby-1.7.6/lib/ruby/gems/shared/gems/sidekiq-2.16.1/lib/sidekiq/middleware/server/retry_jobs.rb:62:in `call'
/Users/john/.rbenv/versions/jruby-1.7.6/lib/ruby/gems/shared/gems/sidekiq-2.16.1/lib/sidekiq/middleware/chain.rb:121:in `invoke'
/Users/john/.rbenv/versions/jruby-1.7.6/lib/ruby/gems/shared/gems/sidekiq-2.16.1/lib/sidekiq/middleware/server/logging.rb:11:in `call'
/Users/john/.rbenv/versions/jruby-1.7.6/lib/ruby/gems/shared/gems/sidekiq-2.16.1/lib/sidekiq/logging.rb:22:in `with_context'
/Users/john/.rbenv/versions/jruby-1.7.6/lib/ruby/gems/shared/gems/sidekiq-2.16.1/lib/sidekiq/middleware/server/logging.rb:7:in `call'
/Users/john/.rbenv/versions/jruby-1.7.6/lib/ruby/gems/shared/gems/sidekiq-2.16.1/lib/sidekiq/middleware/chain.rb:121:in `invoke'
org/jruby/RubyProc.java:271:in `call'
/Users/john/.rbenv/versions/jruby-1.7.6/lib/ruby/gems/shared/gems/sidekiq-2.16.1/lib/sidekiq/middleware/chain.rb:124:in `invoke'
/Users/john/.rbenv/versions/jruby-1.7.6/lib/ruby/gems/shared/gems/sidekiq-2.16.1/lib/sidekiq/processor.rb:47:in `process'
/Users/john/.rbenv/versions/jruby-1.7.6/lib/ruby/gems/shared/gems/sidekiq-2.16.1/lib/sidekiq/processor.rb:102:in `stats'
/Users/john/.rbenv/versions/jruby-1.7.6/lib/ruby/gems/shared/gems/sidekiq-2.16.1/lib/sidekiq/processor.rb:46:in `process'
/Users/john/.rbenv/versions/jruby-1.7.6/lib/ruby/gems/shared/gems/sidekiq-2.16.1/lib/sidekiq/processor.rb:83:in `do_defer'
/Users/john/.rbenv/versions/jruby-1.7.6/lib/ruby/gems/shared/gems/sidekiq-2.16.1/lib/sidekiq/processor.rb:37:in `process'
org/jruby/RubyKernel.java:1961:in `public_send'
/Users/john/.rbenv/versions/jruby-1.7.6/lib/ruby/gems/shared/gems/celluloid-0.15.2/lib/celluloid/calls.rb:25:in `dispatch'
/Users/john/.rbenv/versions/jruby-1.7.6/lib/ruby/gems/shared/gems/celluloid-0.15.2/lib/celluloid/calls.rb:122:in `dispatch'
/Users/john/.rbenv/versions/jruby-1.7.6/lib/ruby/gems/shared/gems/celluloid-0.15.2/lib/celluloid/actor.rb:322:in `handle_message'
/Users/john/.rbenv/versions/jruby-1.7.6/lib/ruby/gems/shared/gems/celluloid-0.15.2/lib/celluloid/actor.rb:416:in `task'
/Users/john/.rbenv/versions/jruby-1.7.6/lib/ruby/gems/shared/gems/celluloid-0.15.2/lib/celluloid/tasks.rb:55:in `initialize'
/Users/john/.rbenv/versions/jruby-1.7.6/lib/ruby/gems/shared/gems/celluloid-0.15.2/lib/celluloid/tasks.rb:47:in `initialize'
/Users/john/.rbenv/versions/jruby-1.7.6/lib/ruby/gems/shared/gems/celluloid-0.15.2/lib/celluloid/tasks/task_fiber.rb:13:in `create'
```

**Comment by jjb** [comment]
looks like issue is fixed by this commit:

https://github.com/mhfs/devise-async/commit/52c483bfd26a8a09919f061b2ce9ad6252945137

![image](https://cloud.githubusercontent.com/assets/6097/6220438/4762d1de-b604-11e4-96d9-093fc32b9d2e.png)

**Comment by baschtl** [comment]
@jjb Great!

Could somebody else confirm this?
